---
galaxy_info:
  role_name: role_pytest_reports
  author: Your Name
  description: Processes pytest results, formats XML output, and generates consolidated reports
  company: Your Company
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
    - name: EL  # Enterprise Linux
      versions:
        - all

  galaxy_tags:
    - testing
    - reporting
    - pytest
    - development

dependencies: []
