- name: Delete directory
  hosts: "{{ target_vm | default('kvm_guests') }}"  # Target specific VM or default to kvm_guests group
  # You can also target a specific group from your inventory like 'hosts: webservers'
  become: yes  # Use sudo privileges

  tasks:
  - name: Remove directories
    ansible.builtin.file:
      path: "{{ item }}"
      state: absent
    loop:
      - /home/kenneth/uvprog2025/Ollama-Downloads
      - /home/kenneth/uvprog2025/Deeplearning-Langchain-Llm-Course
    register: delete_result

  - name: Print deletion results
    debug:
      msg: "Directory {{ item.item }} deletion status: {{ item.changed }}"
    loop: "{{ delete_result.results }}"
