- name: Delete directory
  hosts: "{{ target_vm | default('kvm_guests') }}"  # Target specific VM or default to kvm_guests group
  # You can also target a specific group from your inventory like 'hosts: webservers'
  become: yes  # Use sudo privileges

  tasks:
    - name: Remove directory
      ansible.builtin.file:
        path: /home/kenneth/uvprog2025/Ollama-Downloads
        state: absent
      register: delete_result

    - name: Print deletion result
      debug:
        msg: "Directory deletion status: {{ delete_result }}"
