---

#    time ansible-playbook _download_iso.yml
#    time ansible-playbook _download_iso.yml -v -e "target_vm=['kvm-a1-1-u2004-6']"
#    time ansible-playbook _download_iso.yml -v -e "target_vm=['kvm-a1-2-u2204-5']"
#    time ansible-playbook _download_iso.yml -v -e "target_vm=['kvm-a1-3-u2404-1']"
#    time ansible-playbook _download_iso.yml -v -e "target_vm=['kvm-a1-4-u2410']"

- name: Download ISO for building images via virt-install
  hosts: kvm_host
  become: true
  vars:
    username: "kenneth"
    isodir: "Downloads/ISO"
  roles:
    - role_download_iso
