---

#    time ansible-playbook kvm_guest_vms.yml

#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-1-u2004-6']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-2-u2204-5']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-3-u2404-1']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-4-u2410']"   -e "include_testme=false"

#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-1-u2004-6']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-2-u2204-5']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-3-u2404-1']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a1-4-u2410']"   -e "include_testme=true"

#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-1-u2004-6']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-2-u2204-5']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-3-u2404-1']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-4-u2410']"   -e "include_testme=false"

#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-1-u2004-6']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-2-u2204-5']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-3-u2404-1']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a2-4-u2410']"   -e "include_testme=true"


#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-1-u2004-6']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-2-u2204-5']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-3-u2404-1']" -e "include_testme=false"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-4-u2410']"   -e "include_testme=false"

#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-1-u2004-6']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-2-u2204-5']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-3-u2404-1']" -e "include_testme=true"
#    time ansible-playbook kvm_guest_vms.yml -v -e "target_vm=['kvm-a3-4-u2410']"   -e "include_testme=true"

- name: Bring up VMs
  hosts: kvm_host
  become: true
  roles:
    - role_bringup_vms

- name: Install packages on the VMs
  hosts: "{{ target_vm | default('kvm_guests') }}"
  become: true
  vars:
    ollama_models_path: "/usr/share/ollama/.ollama/models"
    virtiofs_tag: "host_models_to_vm"
    username: "kenneth"
  roles:
    - role_common
    - role_install_ollama

- name: Provide a shared folder of ollma models from kvm host to VMs
  hosts: kvm_host
  become: true
  vars:
    ollama_models_path: "/usr/share/ollama/.ollama/models"
  roles:
    - role_share_ollama_models

- name: Git clone projects from github and initiale the .venv
  hosts: "{{ target_vm | default('kvm_guests') }}"
  become: true
  vars:
    username: "kenneth"
    uvprog: "uvprog2025"
  roles:
    - role_load_uvprog2025
