---

#    time ansible-playbook load_uvprog2025.yml
#    time ansible-playbook load_uvprog2025.yml -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -e "include_testme=true"

#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-1-u2004-6']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-2-u2204-5']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-3-u2404-1']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-4-u2410']"   -e "include_testme=false"

#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-1-u2004-6']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-2-u2204-5']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-3-u2404-1']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-4-u2410']"   -e "include_testme=true"

#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-1-u2004-6']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-2-u2204-5']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-3-u2404-1']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-4-u2410']"   -e "include_testme=false"

#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-1-u2004-6']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-2-u2204-5']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-3-u2404-1']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a2-4-u2410']"   -e "include_testme=true"

#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-1-u2004-6']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-2-u2204-5']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-3-u2404-1']" -e "include_testme=false"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-4-u2410']"   -e "include_testme=false"

#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-1-u2004-6']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-2-u2204-5']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-3-u2404-1']" -e "include_testme=true"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a3-4-u2410']"   -e "include_testme=true"

- name: Bring up VMs
  hosts: kvm_host
  become: true
  roles:
    - role_bringup_vms

- name: Git clone projects from github and initiale the .venv
  hosts: "{{ target_vm | default('kvm_guests') }}"
  become: true
  serial: 8
  vars:
    username: "kenneth"
    uvprog: "uvprog2025"
    format_xml: true
  pre_tasks:
    - name: Get user home directory
      include_role:
        name: role_common
        tasks_from: user_info.yml
      tags: always
  roles:
    - { role: role_load_uvprog2025, tags: ['load'] }
    - { role: role_pytest_reports, tags: ['reports', 'format', 'generate', 'consolidate'] }
  post_tasks:
    - name: Notify completion
      debug:
        msg: "Pytest report processing completed successfully"
