---

#    time ansible-playbook load_uvprog2025.yml
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-1-u2004-6']"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-2-u2204-5']"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-3-u2404-1']"
#    time ansible-playbook load_uvprog2025.yml -v -e "target_vm=['kvm-a1-4-u2410']"

- name: Bring up VMs
  hosts: kvm_host
  become: true
  roles:
    - role_bringup_vms

- name: Git clone projects from github and initiale the .venv
  hosts: "{{ target_vm | default('kvm_guests') }}"
  become: true
  vars:
    username: "kenneth"
    uvprog: "uvprog2025"
  roles:
    - role_load_uvprog2025
