---

#    time ansible-playbook  shutdown_vms.yml

#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-a1-1-u2004-6']"
#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-a1-2-u2204-5']"
#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-a1-3-u2404-1']"
#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-a1-4-u2410']"

#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-b1-1-u2004-6']"
#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-b1-2-u2204-5']"
#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-b1-3-u2404-1']"
#    time ansible-playbook shutdown_vms.yml -v -e "target_vm=['kvm-b1-4-u2410']"


- name: Shutdown VM$
  hosts: kvm_host
  become: true
  become_method: "ansible.builtin.sudo"
  gather_facts: no

  roles:
    - role_shutdown_vms
