---
- name: Get host information
  setup:
    gather_subset: ['!all', 'min']

- name: Get VM status and check existence
  command: virsh domstate {{ item }}
  register: vm_status
  changed_when: false
  failed_when: false
  with_items: "{{ target_vm | default(groups['kvm_guests']) }}"

- name: Filter out localhost from target VMs
  set_fact:
    filtered_vms: "{{ vm_status.results | selectattr('item', 'ne', inventory_hostname) | list }}"

- name: Identify non-existent VMs
  fail:
    msg: "VM {{ item.item }} does not exist on the host"
  when: item.rc != 0
  with_items: "{{ filtered_vms }}"

- name: Start VM if not running
  block:
    - name: Log current status
      debug:
        msg: "VM {{ item.item }} status: {{ item.stdout }}"
      with_items: "{{ filtered_vms }}"

    - name: Attempt to start VM
      command: virsh start {{ item.item }}
      register: start_result
      when: item.stdout != "running"
      with_items: "{{ filtered_vms }}"

    - name: Wait for VM to start
      command: virsh domstate {{ item.item }}
      register: check_status
      until: check_status.stdout == "running"
      retries: "{{ kvm_monitor_max_attempts }}"
      delay: "{{ kvm_monitor_wait_time }}"
      when: item.stdout != "running"
      with_items: "{{ filtered_vms }}"

    - name: Report final status
      debug:
        msg: "VM {{ item.item }} final status: {{ check_status.stdout | default(item.stdout) }}"
      with_items: "{{ filtered_vms }}"

    - name: Verify VM is running
      fail:
        msg: "Failed to start VM {{ item.item }} after {{ kvm_monitor_max_attempts }} attempts"
      when:
        - item.stdout != "running"
        - check_status.stdout is defined
        - check_status.stdout != "running"
      with_items: "{{ filtered_vms }}"

    - name: Skip IP check and directly test SSH connectivity
      debug:
        msg: "Skipping domifaddr check and proceeding directly to SSH connectivity test"

    - name: Pause briefly to allow VM network services to start
      pause:
        seconds: 10
      when: item.stdout != "running"
      with_items: "{{ filtered_vms }}"

    - name: Wait for SSH to be available on all VMs
      wait_for:
        host: "{{ hostvars[item.item]['ansible_host'] }}"
        port: 22
        state: started
        delay: 5
        timeout: 300
      delegate_to: localhost
      with_items: "{{ filtered_vms }}"

    - name: Test SSH connection to ensure VMs are truly ready
      ping:
      delegate_to: "{{ item.item }}"
      register: ping_result
      retries: 10
      delay: 5
      until: ping_result is successful
      with_items: "{{ filtered_vms }}"

    - name: Final VM readiness report
      debug:
        msg: "VM {{ item.item.item }} is fully booted and SSH is ready"
      with_items: "{{ ssh_test.results }}"
      when: ssh_test.results is defined

  rescue:
    - name: Log failure details
      debug:
        msg: "Failed to start VMs or establish SSH connections. Check error messages for details."
