# role_bringup_vms/meta/main.yml
---
galaxy_info:
  role_name: role_bringup_vms
  author: Kenneth Wong
  description: Ensures KVM virtual machines are running
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kvm
    - virtualization
    - system

dependencies: []