---
# Tasks for generating test reports

# Debug script path
- name: Debug report script existence
  stat:
    path: "{{ role_path }}/files/enhanced_generate_report.sh"
  register: script_stat
  delegate_to: localhost

- name: Show script status
  debug:
    msg:
      - "Script exists: {{ script_stat.stat.exists }}"
      - "Script path: {{ role_path }}/files/enhanced_generate_report.sh"
  delegate_to: localhost

# First, copy the report generation script to the target
- name: Copy report generation script
  copy:
    src: "{{ role_path }}/files/enhanced_generate_report.sh"
    dest: "{{ user_home.stdout }}/enhanced_generate_report.sh"
    mode: '0755'
  become: yes
  become_user: "{{ username }}"

# Then run the enhanced script on each guest VM
- name: Generate enhanced test reports on guest VM
  shell: "./enhanced_generate_report.sh {{ user_home.stdout }}/{{ uvprog }}"
  args:
    chdir: "{{ user_home.stdout }}"
  become: yes
  become_user: "{{ username }}"

# Debug to verify reports were created
- name: Check if reports were created
  stat:
    path: "{{ user_home.stdout }}/{{ uvprog }}/test_report.md"
  register: report_file
  become: yes
  become_user: "{{ username }}"

- name: Debug report file status
  debug:
    msg:
      - "Report file exists: {{ report_file.stat.exists | default(false) }}"
      - "Path checked: {{ user_home.stdout }}/{{ uvprog }}/test_report.md"
      - "File size: {{ report_file.stat.size | default('N/A') }}"
