# setup_guest_vms/meta/main.yml
---
galaxy_info:
  role_name: role_load_uvprog2025
  author: Kenneth Wong
  description:
  license: MIT
  min_ansible_version: 2.9
  platforms:
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - kvm
    - virtualization
    - system

dependencies: []
